/* ============================================================
   CYBERGUARD ACADEMY — Bank Soal Kuis (108 soal, 6 kategori)
   Dipakai oleh js/quiz.js pada halaman quiz.html
   ============================================================ */
(function () {
  'use strict';

  window.QUIZ_DATA = [
    /* ===================== FUNDAMENTAL ===================== */
    {
      key: 'fundamental',
      label: 'Fundamental',
      icon: 'ic-book',
      color: 'var(--cyan)',
      questions: [
        { q: 'Dalam CIA Triad, memastikan data hanya bisa diakses pihak yang berhak disebut sebagai…',
          opts: ['Ketersediaan', 'Integritas', 'Kerahasiaan', 'Keaslian'],
          correct: 2,
          explain: 'Confidentiality (kerahasiaan) melindungi data dari akses yang tidak berhak — dijaga dengan enkripsi, kontrol akses, dan least privilege.' },
        { q: 'Serangan ransomware yang mengenkripsi seluruh database menyerang pilar CIA yang mana?',
          opts: ['Confidentiality', 'Integrity', 'Availability', 'Authentication'],
          correct: 2,
          explain: 'Ransomware membuat data tidak dapat diakses → menyerang Availability. Inilah alasan backup dan recovery drill menjadi kontrol paling hemat biaya.' },
        { q: 'SHA-256 termasuk dalam kategori…',
          opts: ['Enkripsi simetris', 'Enkripsi asimetris', 'Fungsi hash satu arah', 'Protokol pertukaran kunci'],
          correct: 2,
          explain: 'SHA-256 adalah função hash satu arah — tidak bisa dibalik menjadi plaintext. Dipakai untuk integritas dan penyimpanan password.' },
        { q: 'AES-256 termasuk dalam kategori…',
          opts: ['Enkripsi simetris', 'Enkripsi asimetris', 'Fungsi hash', 'Tanda tangan digital'],
          correct: 0,
          explain: 'AES adalah cipher block simetris: satu kunci untuk enkripsi dan dekripsi. Cepat dan ideal untuk data berukuran besar.' },
        { q: 'Port default layanan SMB di Windows adalah…',
          opts: ['21', '445', '3306', '3389'],
          correct: 1,
          explain: 'SMB berjalan di port 445. Port 445 rentan terhadap EternalBlue, relay attack, dan exposed shares.' },
        { q: 'CVE-2021-44228 dikenal sebagai…',
          opts: ['Heartbleed', 'Log4Shell', 'EternalBlue', 'Shellshock'],
          correct: 1,
          explain: 'CVE-2021-44228 adalah Log4Shell — kerentanan pada library logging Java yang dieksploitasi masif melalui supply chain.' },
        { q: 'Pada model AAA, komponen yang mencatat aktivitas pengguna adalah…',
          opts: ['Authentication', 'Authorization', 'Accounting', 'Administration'],
          correct: 2,
          explain: 'Accounting merekam apa yang dilakukan pengguna (log, audit trail). Tanpa accounting, investigasi insiden berjalan buta.' },
        { q: 'Serangan ARP poisoning terjadi di lapisan OSI…',
          opts: ['Application (7)', 'Network (3)', 'Data Link (2)', 'Transport (4)'],
          correct: 2,
          explain: 'ARP bekerja di lapisan 2 (Data Link). ARP spoofing dapat membuat attacker menjadi man-in-the-middle dalam satu broadcast domain.' },
        { q: 'DNS menggunakan port default…',
          opts: ['22', '53', '80', '443'],
          correct: 1,
          explain: 'DNS berjalan di port 53. Rentan terhadap poisoning, tunneling exfiltration, dan typosquatting.' },
        { q: '"Zero-day" berarti…',
          opts: ['Celah yang belum diketahui vendor / belum ada patch', 'Celah tanpa kode exploit', 'Server tanpa firewall', 'Data dihapus permanen'],
          correct: 0,
          explain: 'Zero-day adalah kerentanan yang belum diketahui vendor sehingga belum ada perbaikan resminya — nilainya mahal di pasar gelap.' },
        { q: 'Skor keparahan kerentanan 0-10 beserta vektor penjelasnya dikenal sebagai…',
          opts: ['CWE', 'CVE', 'CVSS', 'EPSS'],
          correct: 2,
          explain: 'CVSS (Common Vulnerability Scoring System) memberi skor 0-10 dengan vektor; 10 = paling kritis. 2026 mengombinasikannya dengan EPSS untuk prioritas.' },
        { q: 'EPSS digunakan untuk memperkirakan…',
          opts: ['Kemungkinan kerentanan dieksploitasi di dunia nyata', 'Jumlah gaji analyst', 'Lebar bandwidth', 'Pengganti CVE'],
          correct: 0,
          explain: 'EPSS (Exploit Prediction Scoring System) menilai probabilitas eksploitasi nyata — pelengkap CVSS untuk mengatur prioritas patch.' },
        { q: '"Lateral movement" berarti…',
          opts: ['Bergerak dari satu host ke host lain setelah akses awal', 'Berpindah antar jaringan publik', 'Menghapus semua log', 'Mengatur ulang patch'],
          correct: 0,
          explain: 'Lateral movement adalah pergerakan antar host dalam jaringan setelah mendapatkan akses awal — misalnya menyebar ke server lain.' },
        { q: '"Persistence" dalam konteks penyerang berarti…',
          opts: ['Membersihkan jejak', 'Mekanisme agar akses bertahan setelah reboot/patch', 'Menguatkan firewall', 'Backup data'],
          correct: 1,
          explain: 'Persistence adalah cara penyerang tetap memegang akses meskipun sistem di-restart atau di-patch, misalnya lewat service atau scheduled task.' },
        { q: 'Strategi backup 3-2-1 berarti…',
          opts: ['3 backup, 2 lokasi, 1 jenis media', '3 salinan data, 2 media berbeda, 1 di luar lokasi', '3 disk, 2 server, 1 cloud', '3 data, 2 hash, 1 enkripsi'],
          correct: 1,
          explain: '3-2-1: tiga salinan data, dua media berbeda, satu salinan disimpan di luar lokasi. Basis pertahanan paling murah terhadap ransomware.' },
        { q: 'Prinsip "least privilege" berarti…',
          opts: ['Memberi hak berlebih demi kenyamanan', 'Hak akses seminimal mungkin sesuai tugas', 'Semua admin punya akses root', 'Tidak perlu pencatatan log'],
          correct: 1,
          explain: 'Least privilege membatasi akses hanya yang diperlukan pekerjaan — memperkecil dampak kompromi dan kesalahan manusia.' },
        { q: 'Mencoba satu atau sedikit password umum ke banyak akun sekaligus disebut…',
          opts: ['Credential stuffing', 'Password spraying', 'Phishing', 'DDoS'],
          correct: 1,
          explain: 'Password spraying memakai satu password umum ke banyak akun untuk menghindari lockout. Berbeda dengan credential stuffing yang memakai password curian.' },
        { q: 'Phishing yang menyamar sebagai atasan/eksekutif untuk meminta transfer dana disebut…',
          opts: ['Vishing', 'Smishing', 'BEC (Business Email Compromise)', 'Spear phishing biasa'],
          correct: 2,
          explain: 'BEC memalsukan identitas eksekutif via email untuk menipu korban melakukan transfer dana atau membocorkan data.' }
      ]
    },

    /* ===================== TOOLS ===================== */
    {
      key: 'tools',
      label: 'Katalog Tools',
      icon: 'ic-wrench',
      color: 'var(--lime)',
      questions: [
        { q: 'Perintah Nmap untuk mendeteksi versi layanan adalah…',
          opts: ['nmap -sn', 'nmap -sV', 'nmap -p 80', 'nmap -O 0'],
          correct: 1,
          explain: '-sV menampilkan versi layanan, contoh: OpenSSH 8.2p1, Apache httpd 2.4.41. Kunci untuk menemukan CVE.' },
        { q: 'nmap -sn digunakan untuk…',
          opts: ['Host discovery tanpa port scan', 'Full port scan', 'Deteksi versi layanan', 'Web vulnerability scan'],
          correct: 0,
          explain: '-sn (scan no port) hanya mencari host hidup via ICMP/TCP ACK — cepat memetakan jaringan di fase recon.' },
        { q: 'Flag SQLMap untuk mendata seluruh database adalah…',
          opts: ['--tables', '--dump', '--dbs', '--level'],
          correct: 2,
          explain: '--dbs (databases) menampilkan nama database; lanjutkan dengan --tables lalu --dump untuk mengekstrak data.' },
        { q: 'Pada Metasploit, perintah untuk mencari modul exploit adalah…',
          opts: ['use', 'exploit', 'search', 'jobs'],
          correct: 2,
          explain: 'search menemukan modul (mis. search samba), lalu gunakan perintah use untuk mengaktifkannya.' },
        { q: 'Burp Suite terutama digunakan untuk…',
          opts: ['Scan Wi-Fi', 'Menguji dan menganalisis aplikasi web', 'Forensik memori', 'Manajemen SIEM'],
          correct: 1,
          explain: 'Burp Suite adalah proxy interceptor untuk aplikasi web: memotong request, memodifikasi, dan melakukan scanning otomatis.' },
        { q: 'Wireshark digunakan untuk…',
          opts: ['Menganalisis paket jaringan secara detail', 'Enumerasi direktori web', 'Crack password', 'Brute force SSH'],
          correct: 0,
          explain: 'Wireshark melakukan packet capture dan analisis protokol — andalan untuk troubleshooting dan forensik jaringan.' },
        { q: 'hashcat dengan flag -m 0 berarti mode…',
          opts: ['SHA-256', 'MD5', 'bcrypt', 'NTLM'],
          correct: 1,
          explain: 'Mode 0 adalah MD5. Untuk NTLM pakai -m 1000, bcrypt pakai -m 3200.' },
        { q: 'Nikto digunakan untuk…',
          opts: ['Web server scanner dan cek kerentanan/CVE', 'Pengelola SIEM', 'Pentest Wi-Fi', 'Manajemen firewall'],
          correct: 0,
          explain: 'Nikto memindai web server mencari file berbahaya, konfigurasi buruk, dan CVE sesuai versi server.' },
        { q: 'Gobuster dengan mode dir digunakan untuk…',
          opts: ['Enumerasi subdomain', 'Enumerasi direktori/URL aplikasi web', 'Scan port', 'Crack hash'],
          correct: 1,
          explain: 'gobuster dir -u http://host -w wordlist.txt mencari direktori tersembunyi seperti /admin/, /backup/, /config/.' },
        { q: 'Hydra adalah tool untuk…',
          opts: ['Password brute-force pada banyak layanan (SSH, FTP, HTTP)', 'SQL injection', 'Packet capture', 'Reverse engineering'],
          correct: 0,
          explain: 'Hydra menguji login brute-force: hydra -l admin -P wordlist.txt ssh://host — terkenal cepat dan mendukung banyak protokol.' },
        { q: 'Perintah curl -I akan…',
          opts: ['Mengunduh seluruh file', 'Menampilkan hanya header HTTP', 'Mengirim payload POST', 'Mengenkripsi traffic'],
          correct: 1,
          explain: '-I (HEAD) mengambil header saja — cepat untuk memeriksa server, redirect, dan security headers.' },
        { q: 'Tool Linux untuk melihat koneksi jaringan aktif adalah…',
          opts: ['nslookup', 'netstat / ss', 'dig', 'traceroute'],
          correct: 1,
          explain: 'netstat atau ss menampilkan koneksi dan port terbuka — dipakai mendeteksi koneksi mencurigakan seperti beacon C2.' },
        { q: 'Suricata adalah…',
          opts: ['IDS/IPS berbasis signature dan rule', 'Antivirus komersial', 'Reverse proxy', 'Load balancer'],
          correct: 0,
          explain: 'Suricata mendeteksi (dan dapat memblokir) traffic mencurigakan memakai rule seperti Snort — contoh dipakai membaca pcap pada modul Defensive.' },
        { q: 'Contoh tool SIEM yang umum di pasar adalah…',
          opts: ['Splunk, Elasticsearch ELK, IBM QRadar', 'Burp, ZAP, Postman', 'Metasploit, Cobalt Strike', 'Wireshark, tcpdump, Nmap'],
          correct: 0,
          explain: 'SIEM (Splunk, Elasticsearch, QRadar, Wazuh) mengagregasi dan mengkorelasikan log dari seluruh environment untuk deteksi dan alert.' },
        { q: 'searchsploit digunakan untuk…',
          opts: ['Mencari exploit di database Exploit-DB', 'Mencari port terbuka', 'Membaca CVE saja', 'Menemukan direktori web'],
          correct: 0,
          explain: 'searchsploit mencari exploit lokal dari Exploit-DB — memudahkan membuktikan CVE terhadap versi software target.' },
        { q: 'tcpdump berfungsi untuk…',
          opts: ['Capture paket jaringan dari command line', 'Aplikasi web pentest', 'Membuat wordlist', 'Enkripsi disk'],
          correct: 0,
          explain: 'tcpdump adalah CLI packet capture ringan — pasangan Wireshark untuk server tanpa GUI.' },
        { q: 'John the Ripper dan hashcat dipakai bersama untuk…',
          opts: ['Cracking password hash', 'Forensik memori', 'OSINT', 'Nmap scanning'],
          correct: 0,
          explain: 'Keduanya melakukan password cracking: hashcat memakai GPU (super cepat), john unggul dalam mode wordlist+rule dan banyak format.' },
        { q: 'Urutan pemindaian yang paling efisien untuk menemukan host hidup di LAN adalah…',
          opts: ['nmap -sn 192.168.1.0/24', 'sqlmap --dbs', 'hydra ssh', 'nikto -h host'],
          correct: 0,
          explain: '-sn melakukan host discovery terlebih dahulu, lalu baru scan port pada host yang hidup — menghemat waktu di fase recon.' }
      ]
    },

    /* ===================== OFFENSIVE ===================== */
    {
      key: 'offensive',
      label: 'Offensive',
      icon: 'ic-arrows',
      color: 'var(--rose)',
      questions: [
        { q: 'Fase pertama dalam alur penetration testing adalah…',
          opts: ['Exploitation', 'Reconnaissance (pengumpulan informasi)', 'Persistence', 'Reporting'],
          correct: 1,
          explain: 'Semua alur pentest dimulai dari reconnaissance — memahami medan, target, dan vektor sebelum menyerang.' },
        { q: 'Tujuan utama port scanning adalah…',
          opts: ['Menghentikan serangan', 'Menemukan layanan dan port terbuka pada host', 'Melindungi server', 'Mengenkripsi traffic'],
          correct: 1,
          explain: 'Port scan memetakan layanan yang berjalan (SSH, HTTP, SMB, dll) sehingga attacker tahu titik masuk potensial.' },
        { q: 'SQL injection terjadi ketika…',
          opts: ['Input user digabung langsung ke query database tanpa sanitasi', 'Password terlalu pendek', 'Port 443 ditutup', 'Log tidak dirotasi'],
          correct: 0,
          explain: 'SQLi mengeksploitasi input yang langsung diproses query — dapat membaca/menghapus/mengontrol database.' },
        { q: 'XSS (Cross-Site Scripting) mengeksploitasi…',
          opts: ['Kerentanan sisi server', 'Input yang dirender tanpa sanitasi sehingga mengeksekusi skrip di browser korban', 'Enkripsi lemah', 'Rate limit'],
          correct: 1,
          explain: 'XSS menyisipkan skrip berbahaya ke halaman yang dilihat korban — bisa mencuri cookie sesi, keylogger, atau deface.' },
        { q: 'CSRF (Cross-Site Request Forgery) memanfaatkan…',
          opts: ['Sesi aktif korban untuk memaksa aksi tanpa sepengetahuan korban', 'SQL injection', 'Brute force', 'Spoofing DNS'],
          correct: 0,
          explain: 'CSRF memaksa browser korban yang sudah terautentikasi mengirim request berbahaya, misalnya transfer dana.' },
        { q: 'Reverse shell berarti…',
          opts: ['Host korban terkoneksi kembali ke mesin attacker', 'Attacker menunggu koneksi dari korban tanpa inisiatif', 'Shell tanpa akses', 'VPN terbalik'],
          correct: 0,
          explain: 'Pada reverse shell, korban menginisiasi koneksi keluar ke attacker — efektif menembus firewall inbound.' },
        { q: 'Privilege escalation adalah upaya…',
          opts: ['Mendapatkan hak akses lebih tinggi dari yang sudah dimiliki', 'Menurunkan bandwidth', 'Menghapus user', 'Mengubah password harian'],
          correct: 0,
          explain: 'Dari user biasa menjadi root/SYSTEM, biasanya lewat misconfig, service yang dapat dieksploitasi, atau kredensial bocor.' },
        { q: 'Password spraying memakai…',
          opts: ['Banyak password pada satu akun', 'Satu atau sedikit password umum pada banyak akun', 'Hanya karakter alfabet', 'Hanya password ber-hash'],
          correct: 1,
          explain: 'Spraying meminimalkan percobaan per akun untuk menghindari policy lockout — berbeda dengan brute force konvensional.' },
        { q: 'Credential stuffing memakai…',
          opts: ['Password dari database hasil breach terhadap akun lain', 'Wordlist generik', 'Brute force WiFi', 'Social engineering'],
          correct: 0,
          explain: 'Credential stuffing mencoba kombinasi email:password curian dari breach lain — karena banyak orang memakai password sama.' },
        { q: 'Attack MITM (man-in-the-middle) terjadi ketika…',
          opts: ['Attacker menyisipkan diri di tengah komunikasi dua pihak', 'Sertifikat dihapus', 'Cache dibaca', 'Port dibuka'],
          correct: 0,
          explain: 'MITM membuat attacker dapat membaca dan memodifikasi traffic yang melewatinya, misalnya via ARP spoofing.' },
        { q: 'Tool favorit untuk menemukan path/direktori tersembunyi aplikasi web adalah…',
          opts: ['gobuster atau nikto', 'ping sweep', 'dig', 'whoami'],
          correct: 0,
          explain: 'gobuster dir dan nikto melakukan enumerasi konten web — menemukan /admin, /backup, atau file config yang terbuka.' },
        { q: 'Payload dalam exploit adalah…',
          opts: ['Muatan yang dijalankan setelah exploit berhasil', 'Header HTTP', 'Package installer', 'Kunci enkripsi'],
          correct: 0,
          explain: 'Payload adalah efek dari exploit — misalnya reverse shell, keylogger, atau perintah yang dijalankan sistem korban.' },
        { q: 'Setelah mendapat akses awal, petualangan menjelajahi jaringan internal disebut…',
          opts: ['Lateral movement dan post-exploitation', 'Reconnaissance', 'Fuzzing', 'Decompilation'],
          correct: 0,
          explain: 'Post-exploitation: mempertahankan akses, mengumpulkan data, lalu bergerak lateral ke sistem lain demi target akhir.' },
        { q: '"Persistence" yang dipasang penyerang bertujuan…',
          opts: ['Akses tetap bertahan setelah reboot atau perubahan sistem', 'Mempercepat backup', 'Menjaga patching', 'Merotasi log'],
          correct: 0,
          explain: 'Bentuknya beragam: scheduled task, service, registry, atau backdoor — agar akses tidak hilang bila sistem di-restart.' },
        { q: 'Spear phishing berbeda dari phishing massal karena…',
          opts: ['Target terarah dengan personalisasi sesuai korban', 'Broadcast massal tanpa personalisasi', 'Hanya lewat telepon', 'Hanya lewat SMS'],
          correct: 0,
          explain: 'Spear phishing dirancang khusus untuk satu target/organisasi — tingkat keberhasilan jauh lebih tinggi dibanding phishing massal.' },
        { q: 'Insecure deserialization dapat mengarah ke…',
          opts: ['Remote Code Execution (RCE)', 'Port blocking', 'Pembuatan akun baru', 'Enkripsi lemah'],
          correct: 0,
          explain: 'Deserialisasi data yang tidak aman bisa mengeksekusi objek/kode berbahaya — masuk jajaran OWASP Top 10.' },
        { q: 'IDOR (Insecure Direct Object Reference) contohnya…',
          opts: ['Mengubah id/user di URL untuk mengakses data milik orang lain', 'Memasukkan skrip XSS', 'Scanning port', 'Enumerasi DNS'],
          correct: 0,
          explain: 'IDOR adalah akses langsung ke objek (order, dokumen, profil) tanpa pengecekan otorisasi — misal /order?id=123 menjadi id=124.' },
        { q: 'Fuzzing adalah teknik…',
          opts: ['Mengirim input acak/malformed untuk menemukan bug dan crash', 'Backup database', 'Forensik disk', 'Rotasi kunci'],
          correct: 0,
          explain: 'Fuzzing mengotomatiskan input tidak valid ke aplikasi untuk menggali bug, crash, atau perilaku tak terduga.' }
      ]
    },

    /* ===================== DEFENSIVE ===================== */
    {
      key: 'defensive',
      label: 'Defensive',
      icon: 'ic-shield-check',
      color: 'var(--lime)',
      questions: [
        { q: 'Fungsi utama SIEM adalah…',
          opts: ['Agregasi, korelasi log, dan alerting terpusat', 'Web Application Firewall', 'Load balancing', 'Backup data'],
          correct: 0,
          explain: 'SIEM mengumpulkan log dari banyak sumber, mengkorelasikan untuk mendeteksi pola serangan, dan memicu alert.' },
        { q: 'Fase pertama model incident response NIST adalah…',
          opts: ['Preparation', 'Detection & Analysis', 'Containment', 'Recovery'],
          correct: 0,
          explain: 'NIST IR: Preparation → Detection & Analysis → Containment → Eradication → Recovery → Lessons Learned. Dimulai dari kesiapan.' },
        { q: 'EDR fokus menyelidiki dan merespons…',
          opts: ['Endpoint (host): proses, file, memory, dan behavior', 'Hanya DNS filtering', 'Hanya segmentasi jaringan', 'Hanya enkripsi email'],
          correct: 0,
          explain: 'EDR memantau behavior endpoint secara real-time — mendeteksi dan mengisolasi host yang terkompromi (mis. run proses powershell mencurigakan).' },
        { q: 'Perbedaan utama IDS dan IPS adalah…',
          opts: ['IDS hanya mendeteksi+alert; IPS aktif memblokir traffic', 'IPS tidak bisa mendeteksi', 'IDS memblokir semua', 'Tidak ada perbedaan'],
          correct: 0,
          explain: 'IDS memberi peringatan; IPS mengambil aksi (drop/reject). IPS umumnya dipasang inline pada jalur traffic.' },
        { q: 'IOC merupakan singkatan dari…',
          opts: ['Indicator of Compromise', 'Internet Operating Center', 'Identity of Certificate', 'Info Object Code'],
          correct: 0,
          explain: 'IOC adalah jejak bahwa sistem telah dibobol — misal hash malware, IP C2, atau domain mencurigakan.' },
        { q: 'MITRE ATT&CK adalah…',
          opts: ['Knowledge base taktik dan teknik adversary', 'Antivirus open source', 'Standar enkripsi', 'Framework audit keuangan'],
          correct: 0,
          explain: 'ATT&CK memetakan taktik (tahapan) dan teknik penyerang — bahasa bersama untuk hunting, deteksi, dan mitigasi.' },
        { q: 'Threat hunting adalah…',
          opts: ['Proaktif mencari ancaman yang belum terdeteksi alert', 'Menunggu alert semata', 'Patch management', 'Menjalankan honeypot saja'],
          correct: 0,
          explain: 'Hunting berasumsi bahwa telah terjadi kompromi — analis mencari jejak dengan hipotesis alih-alih menunggu alert.' },
        { q: 'Hardening berarti…',
          opts: ['Mengurangi permukaan serangan melalui konfigurasi aman', 'Menambah fitur sebanyak mungkin', 'Menghapus seluruh log', 'Membuka semua port'],
          correct: 0,
          explain: 'Hardening menutup layanan tak perlu, menghapus default credential, menerapkan patch, dan mengetatkan konfigurasi.' },
        { q: 'MFA (Multi-Factor Authentication) memvalidasi…',
          opts: ['Dua atau lebih faktor autentikasi yang independen', 'Satu password yang panjang', 'Hanya biometric', 'Hanya email'],
          correct: 0,
          explain: 'MFA memadukan faktor knowledge (password), possession (TOTP/key), dan inherence (biometrik) — menghambat pencurian kredensial.' },
        { q: 'Contoh security header adalah…',
          opts: ['CSP, X-Frame-Options, HSTS', 'SQL, NoSQL, Redis', 'TCP, UDP, ICMP', 'HTML, CSS, JS'],
          correct: 0,
          explain: 'Security headers melindungi browser dari serangan: CSP (XSS), X-Frame-Options (clickjacking), HSTS (SSL stripping).' },
        { q: 'Log autentikasi SSH di Linux umumnya tersimpan di…',
          opts: ['/var/log/auth.log', 'C:\\Windows\\System32\\Logs', '/etc/passwd', '/boot/log.conf'],
          correct: 0,
          explain: 'auth.log mencatat percobaan login (Failed password, Accepted password) — sumber utama deteksi brute force.' },
        { q: 'Honeypot adalah…',
          opts: ['Sistem umpan untuk menarik sekaligus mempelajari attacker', 'Backup server', 'SIEM gratis', 'Aturan firewall'],
          correct: 0,
          explain: 'Honeypot sengaja dibuat terlihat rentan untuk mendeteksi dan mempelajari taktik penyerang tanpa membahayakan aset nyata.' },
        { q: 'Playbook dalam SOC adalah…',
          opts: ['SOP langkah standar untuk menangani tipe alert tertentu', 'Rekaman video serangan', 'Dokumen legal CA', 'Laporan keuangan'],
          correct: 0,
          explain: 'Playbook mempercepat respon: siapa mengerjakan apa, urutan tindakan, dan keputusan eskalasi saat alert tertentu muncul.' },
        { q: 'TTP mengacu pada…',
          opts: ['Tactics, Techniques, and Procedures', 'Total Traffic Protocol', 'Terminal Transfer Process', 'TCP/TLS Platform'],
          correct: 0,
          explain: 'TTP adalah cara penyerang bekerja per tahap — didokumentasikan rapi di MITRE ATT&CK untuk deteksi berbasis perilaku.' },
        { q: 'Fase containment dalam incident response bertujuan…',
          opts: ['Membatasi penyebaran insiden agar tidak meluas', 'Menghapus semua data server', 'Menutup server selamanya', 'Merilis laporan publik'],
          correct: 0,
          explain: 'Containment mengisolasi (seperti memutus jaringan host terinfeksi) agar blast radius serangan tidak membesar.' },
        { q: 'EDR unggul dibanding antivirus tradisional karena…',
          opts: ['Behavior analytics dan response real-time', 'Hanya definisi virus harian', 'Waktu scan lebih cepat', 'Harga lebih murah untuk rumahan'],
          correct: 0,
          explain: 'AV berbasis signature; EDR menganalisis perilaku (att&ck mapping) dan bisa mengisolasi endpoint secara proaktif.' },
        { q: 'Fase eradication berarti…',
          opts: ['Menghapus akar penyebab serangan dari sistem', 'Menambah user baru', 'Berbagi kredensial', 'Merotasi alamat IP publik'],
          correct: 0,
          explain: 'Setelah terkontaminasi, akar penyebab (malware, backdoor, akun jahat) harus dibersihkan tuntas sebelum pemulihan.' },
        { q: 'Praktik terbaik menjaga integritas log dari host yang terkompromi adalah…',
          opts: ['Mengirim log ke server terpusat dan append-only', 'Menyimpan di disk lokal user', 'Membagikan log agar transparan', 'Menghapus log mingguan'],
          correct: 0,
          explain: 'Log yang terpusat dan hanya dapat ditambah tidak bisa dihapus penyerang dari host — bukti investigasi tetap utuh.' }
      ]
    },

    /* ===================== METODOLOGI ===================== */
    {
      key: 'methodology',
      label: 'Metodologi',
      icon: 'ic-target',
      color: 'var(--violet)',
      questions: [
        { q: 'Fase pertama dari kerangka PTES adalah…',
          opts: ['Pre-Engagement Interaction', 'Reconnaissance', 'Scanning', 'Reporting'],
          correct: 0,
          explain: 'PTES dimulai dari interaksi pra-engagement: scope, aturan, kontrak, dan persetujuan sebelum pengujian dilakukan.' },
        { q: 'OWASP Top 10 berisi…',
          opts: ['Risiko keamanan aplikasi web yang paling umum dan kritis', 'Password paling lemah', 'Port standar service', 'Framework pemrograman Java'],
          correct: 0,
          explain: 'OWASP Top 10 memeringkat risiko aplikasi web seperti injection, broken access control, dan security misconfig.' },
        { q: 'Pentest dengan pengetahuan penuh internal (source code, kredensial) disebut…',
          opts: ['White box', 'Black box', 'Gray box', 'Red box'],
          correct: 0,
          explain: 'White box memberi tester akses penuh internal; black box tanpa informasi; gray box kombinasi keduanya.' },
        { q: 'Aturan dan lingkup pengujian dalam kontrak disebut…',
          opts: ['Scope / Rules of Engagement (ROE)', 'Payload', 'Zero-day', 'Patch'],
          correct: 0,
          explain: 'ROE menetapkan host yang boleh diuji, metode, jam kerja, kontak, dan prosedur eskalasi — fondasi legalitas pengujian.' },
        { q: 'PoC (Proof of Concept) adalah…',
          opts: ['Wujud minimal yang membuktikan kerentanan dapat dieksploitasi', 'Password default', 'Sertifikat digital', 'Laporan panjang'],
          correct: 0,
          explain: 'PoC menunjukkan exploitasi benar-benar terjadi — mendukung klaim temuan dengan bukti, bukan sekadar teori.' },
        { q: 'False positive dalam laporan pentest berarti…',
          opts: ['Temuan yang keliru / tidak benar-benar ada', 'CVE berprioritas kritis', 'Backdoor terpasang', 'Exploit berhasil'],
          correct: 0,
          explain: 'False positive adalah hasil deteksi yang ternyata tidak nyata — karena itu verifikasi manual temuan penting.' },
        { q: 'Penilaian tingkat keparahan temuan umumnya memakai…',
          opts: ['CVSS base score plus konteks target', 'Waktu scan', 'Jumlah server', 'Panjang password'],
          correct: 0,
          explain: 'Severity menggabungkan skor CVSS dengan konteks: data yang terkena, ekspos, dan dampak bisnis.' },
        { q: 'Passive reconnaissance berarti…',
          opts: ['Mengumpulkan info tanpa berinteraksi langsung dengan target (OSINT)', 'Full port scan', 'Brute force login', 'Menjalankan exploit'],
          correct: 0,
          explain: 'Pasif memanfaatkan sumber publik (whois, search engine, certificate transparency) tanpa menyentuh target — sulit terdeteksi.' },
        { q: 'Bagian pertama laporan pentest yang baik adalah…',
          opts: ['Executive summary dan temuan kritis terurut prioritas', 'Seluruh output Nmap mentah', 'Source code lengkap', 'Daftar port tanpa konteks'],
          correct: 0,
          explain: 'Direksi membaca executive summary: ringkasan risiko, temuan utama, dan rekomendasi dalam bahasa bisnis.' },
        { q: 'Retest / re-verification dilakukan untuk…',
          opts: ['Memastikan temuan telah diperbaiki setelah client menindaklanjuti', 'Menambah tagihan tanpa alasan', 'Membackup data', 'Memperluas scope tanpa izin'],
          correct: 0,
          explain: 'Retest mengonfirmasi patch/tindakan mitigasi berhasil menutup temuan — kesimpulan resmi penutupan penugasan.' },
        { q: 'Dalam konteks situs ini, landasan hukum Indonesia untuk aktivitas keamanan siber mencakup…',
          opts: ['UU ITE, dan UU PDP untuk perlindungan data', 'Hanya UU KUHP', 'Hanya UU PPh', 'Hanya PP 82'],
          correct: 0,
          explain: 'UU ITE (No. 11/2008 jo. 19/2016) mengatur akses ilegal; UU PDP melindungi data pribadi. Uji hanya dengan otorisasi.' },
        { q: 'Syarat legalitas utama sebelum menguji suatu sistem adalah…',
          opts: ['Izin tertulis dari pemilik sistem (authorization)', 'Memiliki password admin', 'Menggunakan VPN', 'Memiliki alamat IP publik'],
          correct: 0,
          explain: 'Tanpa izin tertulis, pengujian adalah tindak pidana akses ilegal meskipun tujuannya "hanya coba-coba".' },
        { q: 'OSSTMM adalah…',
          opts: ['Standar metodologi pengujian keamanan (Open Source Security Testing Methodology Manual)', 'Tool untuk scan Nmap', 'Sistem operasi Windows', 'Framework desain grafis'],
          correct: 0,
          explain: 'OSSTMM menyediakan kerangka pengujian berbasis operasional — melengkapi PTES dan OWASP WSTG.' },
        { q: 'Aktivitas port scanning masuk ke fase PTES nomor…',
          opts: ['Scanning (fase ketiga)', 'Exploitation', 'Reporting', 'Weaponization'],
          correct: 0,
          explain: 'Urutan PTES: Pre-engagement → Recon → Scanning → Exploitation → Post-exploitation → Reporting.' },
        { q: 'Model yang menggambarkan serangan sebagai rantai tahapan (delivery → exploitation → C2) adalah…',
          opts: ['Cyber Kill Chain (Lockheed Martin)', 'Model OSI', 'PDCA', 'TOGAF'],
          correct: 0,
          explain: 'Cyber Kill Chain memetakan tahapan serangan dari reconnaissance hingga action on objectives — panduan deteksi tiap tahap.' },
        { q: 'Temuan yang baik harus menyertakan…',
          opts: ['Bukti, langkah reproduksi, dan rekomendasi perbaikan', 'Password default akun', 'Alamat attacker', 'Source code lengkap client'],
          correct: 0,
          explain: 'Laporan yang dapat ditindaklanjuti berisi bukti (screenshot/log), cara reproduksi, dampak, dan rekomendasi konkret.' },
        { q: 'Pentest "black box" berarti…',
          opts: ['Tester tidak mendapat informasi internal sama sekali', 'Tester berada di dalam perusahaan', 'Tester membayar biaya uji', 'Tanpa laporan akhir'],
          correct: 0,
          explain: 'Black box menyimulasikan penyerang luar yang hanya tahu target — realistis namun lebih lama dan mahal.' },
        { q: 'Rules of Engagement biasanya mencakup…',
          opts: ['Jam kerja pengujian, host yang diizinkan, kontak darurat, eskalasi', 'Biaya bulanan cloud', 'Password admin', 'SLA penyedia internet'],
          correct: 0,
          explain: 'ROE mencegah overflow dan insiden: kapan boleh menguji, apa yang dilarang, siapa dihubungi bila terjadi sesuatu.' }
      ]
    },

    /* ===================== KARIR ===================== */
    {
      key: 'careers',
      label: 'Karir & Sertifikasi',
      icon: 'ic-user',
      color: 'var(--amber)',
      questions: [
        { q: 'Sertifikasi entry-level yang direkomendasikan untuk memulai karier pentester adalah…',
          opts: ['eJPT dan Security+', 'CISSP', 'CISM', 'CCSP'],
          correct: 0,
          explain: 'eJPT (practical) dan Security+ (foundational) cocok untuk pemula — menjadi batu loncatan menuju OSCP.' },
        { q: 'BTL1 adalah sertifikasi yang fokus pada…',
          opts: ['Blue Team level entry (SOC, incident response)', 'Pengembangan aplikasi web', 'Arsitektur cloud', 'Rekayasa audio'],
          correct: 0,
          explain: 'Blue Team Level 1 menguji praktik SOC dan incident response secara hands-on — pasangan eJPT dari sisi pertahanan.' },
        { q: 'OSCP adalah sertifikasi praktikal yang berfokus pada…',
          opts: ['Penetration testing hands-on di lab', 'Audit keuangan', 'Perancangan hardware', 'Desain user interface'],
          correct: 0,
          explain: 'OSCP terkenal karena ujian praktiknya: menyelesaikan host di lab dalam waktu terbatas — membuktikan keterampilan nyata, bukan sekadar teori.' },
        { q: 'CISSP lebih cocok untuk…',
          opts: ['Manager/arsitek keamanan dengan pengalaman luas', 'Fresh graduate SOC', 'Pengembang game', 'Staf administrasi'],
          correct: 0,
          explain: 'CISSP menguji manajemen keamanan di 8 domain dan mensyaratkan pengalaman kerja — ideal bagi yang ingin naik ke level arsitek/manager.' },
        { q: 'Peran SOC Analyst lebih banyak berfokus pada…',
          opts: ['Monitoring dan triage alert 24/7', 'Pengembangan exploit', 'Hardware pentest', 'Desain web'],
          correct: 0,
          explain: 'SOC Analyst adalah garda depan blue team: memantau telemetri, mengkaji alert, dan menentukan apakah perlu eskalasi.' },
        { q: 'Perbedaan inti red team dan blue team adalah…',
          opts: ['Red = simulasi serangan, Blue = pertahanan dan deteksi', 'Red = pertahanan saja', 'Keduanya sama persis', 'Red = reporting saja'],
          correct: 0,
          explain: 'Red team menemukan dan membuktikan celah; blue team menjaga, mendeteksi, merespons, dan memulihkan.' },
        { q: 'Purple team bertugas…',
          opts: ['Menjembatani red dan blue agar keduanya saling memperbaiki', 'Hanya menyerang', 'Hanya bertahan', 'Menganalisis gaji'],
          correct: 0,
          explain: 'Purple team menggabungkan hasil serangan red team dengan kemampuan deteksi blue team untuk menutup kesenjangan.' },
        { q: 'Platform latihan offensive (CTF/practical) yang populer adalah…',
          opts: ['HackTheBox dan TryHackMe', 'Microsoft Word', 'Canva', 'GitHub Pages saja'],
          correct: 0,
          explain: 'HackTheBox dan TryHackMe memberi lab legal untuk berlatih teknik menyerang dan bertahan — bahan portofolio yang bagus.' },
        { q: 'Menulis write-up setelah menyelesaikan lab/CTF bermanfaat untuk…',
          opts: ['Portofolio dan memperkuat pemahaman', 'Kompetisi desain', 'Menambah ping internet', 'Backup git'],
          correct: 0,
          explain: 'Write-up menunjukkan kemampuan berpikir dan dokumentasi — sangat disukai perekrut dan membangun portofolio.' },
        { q: 'Bug bounty adalah…',
          opts: ['Program resmi yang memberi reward atas temuan kerentanan', 'Mencari bug dalam game', 'Menjual antivirus', 'Reverse engineering OS tanpa izin'],
          correct: 0,
          explain: 'Bug bounty dilakukan pada program resmi perusahaan dengan aturan jelas — cara legal belajar sekaligus menghasilkan.' },
        { q: 'Gaji junior fresh-graduate keamanan siber di Indonesia umumnya…',
          opts: ['Rp 6-12 juta per bulan', 'Rp 1-2 juta per bulan', 'Rp 25-30 juta per bulan', 'Rp 100 juta per bulan'],
          correct: 0,
          explain: 'Junior umumnya Rp 6-12 juta; SOC berpengalaman Rp 12-25 juta; pentester/arsitek senior jauh lebih tinggi.' },
        { q: 'Kemampuan dasar paling wajib sebelum menyentuh tools keamanan adalah…',
          opts: ['Linux dan networking', 'Desain vektor', 'Bahasa asing tingkat lanjut', 'Akuntansi'],
          correct: 0,
          explain: 'Linux (CLI) dan networking adalah fondasi semua pekerjaan keamanan — tools hanyalah alat di atasnya.' },
        { q: 'Skill pertama yang dicari perekrut untuk SOC analyst adalah…',
          opts: ['Log analysis, jaringan, dasar monitoring dan forensik', 'Menulis exploit besar', 'Mahir C level expert', 'Ahli SEO'],
          correct: 0,
          explain: 'SOC entry menekankan kemampuan membaca log, memahami trafik, dan prosedur triage sebelum keterampilan lanjutan.' },
        { q: 'Sertifikasi paling dikenal untuk red team tingkat lanjut adalah…',
          opts: ['OSCP', 'ITIL', 'PMP', 'GDSA'],
          correct: 0,
          explain: 'OSCP dianggap standar entry menuju profesional red team; pengejar karir lanjut sering melanjutkan ke OSEP/OSCP+.' },
        { q: 'Write-up portofolio yang etis sebaiknya…',
          opts: ['Menyertakan langkah teknis, temuan, tanpa bocorkan data klien', 'Menampilkan password target', 'Meniru langkah tanpa belajar', 'Meminjam punya orang lain'],
          correct: 0,
          explain: 'Dokumentasikan di lab/platform resmi, jangan pernah membocorkan data atau detail internal klien tanpa izin.' },
        { q: 'Komunitas dan networking membantu karir karena…',
          opts: ['Referensi dan pembelajaran yang lebih cepat', 'Menggantikan kebutuhan belajar', 'Menghindari sertifikasi', 'Menggantikan sistem operasi'],
          correct: 0,
          explain: 'Komunitas memberikan informasi lowongan, mentoring, dan umpan balik yang mempercepat naik kelas.' },
        { q: 'Roadmap belajar yang disarankan situs ini adalah…',
          opts: ['Fundamental → lab → offense/defense → sertifikasi → karir', 'Langsung OSCP tanpa fondasi', 'Hanya membaca berita', 'Menghafal semua tools tanpa teori'],
          correct: 0,
          explain: 'Mulai dari fondasi, bangun lab, praktik offense & defense, lalu sertifikasi entry — barulah melamar posisi junior.' },
        { q: 'Soft skill pelengkap yang bernilai di profesi keamanan adalah…',
          opts: ['Komunikasi jelas dan dokumentasi rapi', 'Suka mencari celah ilegal', 'Menimbun file', 'Selalu login root'],
          correct: 0,
          explain: 'Temuan tanpa komunikasi yang baik bernilai rendah — laporan, presentasi, dan sikap profesional menentukan dampakmu.' }
      ]
    }
  ];
})();